services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  django_gunicorn:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped
