# Generated by Django 5.2.3 on 2025-08-12 02:46

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='response',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
