import random
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    def clean(self):
        """
        First, make sure that if it's a new user, we set an unusable password
        Second, make sure the username is autogenerated and unique
        """
        super().clean()
        creation = not self.pk

        if creation:
            self.set_unusable_password()
        
        # check if user exist or not and make the username unique
        self.username = self.first_name + self.last_name
        if creation:
            while User.objects.filter(username=self.username).exists():
                self.username += str(random.randint(0, 9))
        else:
            while User.objects.filter(username=self.username).exclude(pk=self.pk).exists():
                self.username += str(random.randint(0, 9))