# Generated by Django 5.2.3 on 2025-08-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_global', 'Global Access'), ('access_faculty_wide', 'Faculty Wide Access'), ('access_program_wide', 'Program Wide Access')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_professor',
        ),
    ]
