# Generated by Django 5.2.3 on 2025-07-31 12:06

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_definition', django_jsonform.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, max_length=13, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=13, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=13, null=True)),
                ('thursday', models.CharField(blank=True, max_length=13, null=True)),
                ('friday', models.CharField(blank=True, max_length=13, null=True)),
                ('saturday', models.CharField(blank=True, max_length=13, null=True)),
                ('sunday', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.program')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=1)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.program')),
            ],
        ),
    ]
