# Generated by Django 5.2.3 on 2025-07-31 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.class'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.course'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.schedule'),
        ),
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.course'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('faculty', 'program', 'generation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('faculty', 'program', 'name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('professor', 'course', '_class')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('schedule', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'course')},
        ),
    ]
