# Generated by Django 5.2.3 on 2025-08-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_friday_schedule_fri_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvalationTemplate',
            new_name='EvaluationTemplate',
        ),
    ]
