name: "CD Pipeline"
on:
  workflow_dispatch:

jobs:
  deploy_production:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
      
      - name: Execute deployment script
        run: |
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }} "
              cd prod && git checkout main && git pull && \
              if git diff --name-only HEAD~1 HEAD | grep -qE \"requirements\\.txt|Dockerfile|\\.sh\"; then \
                sudo docker-compose up --build -d && \
                sudo docker image prune -f; \
              fi
            "